const BUILD='v8-4-7-nav-smooth-freepan';
const SHELL_CACHE='rotadefteri-shell-'+BUILD;
const RUNTIME_CACHE='rotadefteri-runtime-'+BUILD;
const TILE_CACHE='rotadefteri-tiles-'+BUILD;
const SHELL=['./','./index.html','./firebase-config.js','./manifest.webmanifest','./icons/icon-180.png','./icons/icon-192.png','./icons/icon-512.png','./icons/brand-mark.svg','./icons/nav-arrow.svg','./icons/phone.svg','./icons/note.svg'];
self.addEventListener('install',event=>{event.waitUntil(caches.open(SHELL_CACHE).then(c=>c.addAll(SHELL)).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('rotadefteri-')&&![SHELL_CACHE,RUNTIME_CACHE,TILE_CACHE].includes(k)).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting()});
async function trimCache(name,maxItems){try{const c=await caches.open(name),keys=await c.keys();if(keys.length>maxItems)await Promise.all(keys.slice(0,keys.length-maxItems).map(k=>c.delete(k)))}catch(_){}}
async function networkFirst(req,cacheName,timeoutMs=5000){const cache=await caches.open(cacheName);const ctrl=typeof AbortController!=='undefined'?new AbortController():null;let timer=null;try{if(ctrl)timer=setTimeout(()=>ctrl.abort(),timeoutMs);const res=await fetch(req,{cache:'reload',signal:ctrl?.signal});if(res&&(res.ok||res.type==='opaque'))cache.put(req,res.clone()).catch(()=>{});return res}catch(e){const hit=await cache.match(req);if(hit)return hit;throw e}finally{if(timer)clearTimeout(timer)}}
async function cacheFirst(req,cacheName){const cache=await caches.open(cacheName),hit=await cache.match(req);if(hit)return hit;const res=await fetch(req);if(res&&(res.ok||res.type==='opaque')){cache.put(req,res.clone()).then(()=>trimCache(cacheName,220)).catch(()=>{})}return res}
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(req.mode==='navigate'){event.respondWith(networkFirst(req,SHELL_CACHE,4000).catch(()=>caches.match('./index.html')));return}const same=url.origin===self.location.origin;const cdn=['unpkg.com','cdn.sheetjs.com','www.gstatic.com','maps.googleapis.com','maps.gstatic.com'].includes(url.hostname);const tile=/\.tile\.openstreetmap\.org$/.test(url.hostname)||/\.tile\.openstreetmap\.fr$/.test(url.hostname)||url.hostname==='tile.openstreetmap.org'||url.hostname==='tile.openstreetmap.fr';if(tile){event.respondWith(cacheFirst(req,TILE_CACHE));return}if(!same&&!cdn)return;if(same){event.respondWith(networkFirst(req,SHELL_CACHE,5000));return}event.respondWith(caches.match(req).then(hit=>hit||fetch(req).then(res=>{if(res&&(res.ok||res.type==='opaque'))caches.open(RUNTIME_CACHE).then(c=>c.put(req,res.clone())).catch(()=>{});return res})))});
